firejail: fix secret-tool
It was failing with this error:

    ERROR: --x11=none specified, but abstract X11 socket still accessible.
    Additional setup required. To block abstract X11 socket you can either:
    * use network namespace in firejail (--net=none, --net=...)
    * add "-nolisten local" to xserver options
    (eg. to your display manager config, or /etc/X11/xinit/xserverrc)

Bug report in firejail: https://github.com/netblue30/firejail/issues/7168